<?php
	ms::meta('combanner_1_text1',$combanner_1_text1);
	ms::meta('combanner_2_text1',$combanner_2_text1);
	ms::meta('combanner_3_text1',$combanner_3_text1);
	ms::meta('combanner_4_text1',$combanner_4_text1);
	ms::meta('combanner_5_text1',$combanner_5_text1);
	ms::meta('combanner_1_text2',$combanner_1_text2);
	ms::meta('combanner_2_text2',$combanner_2_text2);
	ms::meta('combanner_3_text2',$combanner_3_text2);
	ms::meta('combanner_4_text2',$combanner_4_text2);
	ms::meta('combanner_5_text2',$combanner_5_text2);
	ms::meta('combanner_1_text3',$combanner_1_text3);
	ms::meta('combanner_2_text3',$combanner_2_text3);
	ms::meta('combanner_3_text3',$combanner_3_text3);
	ms::meta('combanner_4_text3',$combanner_4_text3);
	ms::meta('combanner_5_text3',$combanner_5_text3);
	
	ms::meta('combanner_middle',$combanner_middle);
	ms::meta('combanner_bottom',$combanner_bottom);